
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./:/code
    env_file:
      - .env.dev
    environment:
      - PG_DATABASE_HOSTNAME=postgres
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:16-3.5
    env_file:
      - .env.dev
    environment:
      - POSTGRES_PASSWORD=${PG_DATABASE_PASSWORD}
      - POSTGRES_USER=${PG_DATABASE_USERNAME}
      - POSTGRES_DB=${PG_DATABASE_NAME}
    volumes:
      - postgres-data:/data
    ports:
      - "5433:5432"

volumes:
  postgres-data:

networks:
  backend: