"""add inverter relationship

Revision ID: 6f2fd6a5d48b
Revises: b54572e7a612
Create Date: 2025-08-02 17:36:55.878456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f2fd6a5d48b'
down_revision: Union[str, None] = 'b54572e7a612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('solar_panel_hourly_records', sa.Column('inverter_id', sa.Integer(), nullable=False))
    op.drop_constraint('solar_panel_hourly_records_solar_panel_id_fkey', 'solar_panel_hourly_records', type_='foreignkey')
    op.create_foreign_key(None, 'solar_panel_hourly_records', 'inverters', ['inverter_id'], ['id'])
    op.drop_column('solar_panel_hourly_records', 'solar_panel_id')
    op.add_column('solar_panels', sa.Column('inverter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'solar_panels', 'inverters', ['inverter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solar_panels', type_='foreignkey')
    op.drop_column('solar_panels', 'inverter_id')
    op.add_column('solar_panel_hourly_records', sa.Column('solar_panel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'solar_panel_hourly_records', type_='foreignkey')
    op.create_foreign_key('solar_panel_hourly_records_solar_panel_id_fkey', 'solar_panel_hourly_records', 'solar_panels', ['solar_panel_id'], ['id'])
    op.drop_column('solar_panel_hourly_records', 'inverter_id')
    # ### end Alembic commands ###