name: CI
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt ruff
      - run: ruff check

  test:
    environment:
      name: testing
    env:
      PG_DATABASE_HOSTNAME: ${{secrets.PG_DATABASE_HOSTNAME}}
      PG_DATABASE_PORT: ${{secrets.PG_DATABASE_PORT}}
      PG_DATABASE_PASSWORD: ${{secrets.PG_DATABASE_PASSWORD}}
      PG_DATABASE_NAME: ${{secrets.PG_DATABASE_NAME}}
      PG_DATABASE_USERNAME: ${{secrets.PG_DATABASE_USERNAME}}
      JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
      JWT_ALGORITHM: ${{secrets.JWT_ALGORITHM}}
      jwt_token_expire_minutes: ${{secrets.jwt_token_expire_minutes}}
      ML_API_URL: ${{secrets.ML_API_URL}}
      CORS_ORIGINS: ${{secrets.CORS_ORIGINS}}
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run pytest
        run: |
          pip install pytest
          pytest
